---
    php_ppa: php5
    doc_root: /vagrant/web
    sys_packages: ["vim","git"]
    dist: precise
    php_packages: ["php5-cli","php5-mcrypt","php5-xdebug","php5-intl","php-apc","php5-mysql","php5-curl"]
