---
# tasks file for role-mailcatcher
- name: Install required software
  apt: pkg={{ item }} state=latest
  with_items:
      - build-essential
      - sqlite3
      - libsqlite3-dev
      - ruby-dev

- name: Install rubygems
  apt: pkg=rubygems state=latest
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_release > 'trusty'

- name: Install Mailcatcher
  # For some reason, "gem: name=mailcatcher" and "command: gem install mailcatcher" fail to get the gem working
  shell: gem install mailcatcher

- name: Create startup script for mailcatcher
  template: src=mailcatcher.j2 dest=/etc/init.d/mailcatcher mode=0755

- name: Mailcatcher will start upon boot
  command: update-rc.d mailcatcher defaults

- name: Make sure Mailcatcher is not running
  command: /etc/init.d/mailcatcher stop

- name: Start mailcatcher properly with the start script
  command: /etc/init.d/mailcatcher start

- name: Configure PHP sendmail to use Mailcatcher
  template: src=mailcatcher.ini.j2 dest=/etc/php5/conf.d/99-mailcatcher.ini owner=root group=root
  notify: restart apache
