parameters     = File.expand_path("../VagrantParameters", __FILE__)
parametersDist = File.expand_path("../VagrantParameters.dist", __FILE__)

if File.exist?(parameters)
  load parameters
else
  load parametersDist
end

Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |v|
        v.name = $name
        v.customize ["modifyvm", :id, "--memory", $memory_size]
  end
  config.vm.provider :vmware_fusion do |v|
        v.vmx["memsize"] = $memory_size
        v.vmx["displayname"] = $name
  end

    config.vm.box = $vm_box
    config.vm.network :private_network, ip: $ip
    config.ssh.forward_agent = true
    config.vm.hostname = $hostname
    config.hostsupdater.aliases = ["pma." + $hostname]

    File.open('ansible/inventories/dev', 'w') do |f|
        f.write "[phansible-web]\n"
        f.write "#{$ip}\n"
    end
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/playbook.yml"
        ansible.inventory_path = "ansible/inventories/dev"
        ansible.limit = 'all'
  end

    config.vm.synced_folder "../", "/vagrant", type: "nfs"
    if Dir.exists?(File.join(Dir.home, ".composer"))
        config.vm.synced_folder "~/.composer", "/home/vagrant/.composer", type: "nfs"
    end
end
