parameters:
#    gdc.example.class: GDC\CoreBundle\Example

services:
#    gdc.example:
#        class: %gdc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    gdc.piface_factory:
        class: GDC\Door\PiFaceFactory
        arguments:
            - %kernel.root_dir%/var/emulator
            - %gdc_use_piface_hardware%

    gdc.piface:
        class: Pkj\Raspberry\PiFace
        factory_service: gdc.piface_factory
        factory_method: createInstance

    gdc.door:
        class: GDC\Door
        arguments:
            - @gdc.piface

    gdc.watchdog_messenger:
        class: GDC\WatchDog\Messenger
        arguments:
            - @mailer
            - %messenger_sender_address%
            - %messenger_sender_name%
            - %messenger_recipient_address%
            - %messenger_recipient_name%

    gdc.watchdog:
        class: GDC\WatchDog\WatchDog
        arguments:
            - @gdc.door
            - @gdc.watchdog_messenger

    gdc.camera_http_client:
        class: Guzzle\Http\Client
        arguments:
            - %camera_url%

    gdc.camera:
        class: GDC\Camera
        arguments:
            - @gdc.camera_http_client
            - %camera_username%
            - %camera_password%

    gdc.command_queue_entry_repository:
        class: GDCBundle\Entity\CommandQueueEntryRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - GDCBundle:CommandQueueEntry

    gdc.command_processor:
        class: GDCBundle\Service\CommandProcessor
        arguments:
            - @gdc.command_queue_entry_repository
            - @event_dispatcher

    gdc.listener:
        class: GDCBundle\Event\TriggerDoorListener
        arguments:
            - @gdc.door
        tags:
            - { name: kernel.event_listener, event: gdc.command_issued, method: onCommandIssued }
