parameters:
    gdc.piface_inputpin_id.door_closed: 0
    gdc.piface_inputpin_id.door_opened: 1
    gdc.piface_inputpin_id.photo_interrupter: 2

    gdc.piface_outputpin_id.motor_trigger: 0

    gdc.door_state_save_path: "%kernel.root_dir%/../web/state/current.json"

services:
    gdc.piface_factory:
        class: GDC\Door\PiFaceFactory
        arguments:
            - %kernel.root_dir%/var/emulator
            - %gdc_use_piface_hardware%

    gdc.piface:
        class: Pkj\Raspberry\PiFace
        factory_service: gdc.piface_factory
        factory_method: createInstance

    gdc.piface_input_pin.door_closed:
        class: Pkj\Raspberry\PiFace\Hardware\Components\InputPin
        factory_service: gdc.piface
        factory_method: getInputPin
        arguments:
            - %gdc.piface_inputpin_id.door_closed%

    gdc.piface_input_pin.door_opened:
        class: Pkj\Raspberry\PiFace\Hardware\Components\InputPin
        factory_service: gdc.piface
        factory_method: getInputPin
        arguments:
            - %gdc.piface_inputpin_id.door_opened%

    gdc.piface_input_pin.photo_interrupter:
        class: Pkj\Raspberry\PiFace\Hardware\Components\InputPin
        factory_service: gdc.piface
        factory_method: getInputPin
        arguments:
            - %gdc.piface_inputpin_id.photo_interrupter%

    gdc.piface_output_pin.motor_trigger:
        class: Pkj\Raspberry\PiFace\Hardware\Components\OutputPin
        factory_service: gdc.piface
        factory_method: getOutputPin
        arguments:
            - %gdc.piface_outputpin_id.motor_trigger%

    gdc.door:
        class: GDC\Door\Door
        arguments:
            - @gdc.piface_input_pin.door_closed
            - @gdc.piface_input_pin.door_opened
            - @gdc.piface_output_pin.motor_trigger

    gdc.watchdog_messenger:
        class: GDC\WatchDog\Messenger
        arguments:
            - @mailer
            - %messenger_sender_address%
            - %messenger_sender_name%
            - %messenger_recipient_address%
            - %messenger_recipient_name%
        tags:
            - { name: kernel.event_listener, event: watchdog.restarted, method: onWatchdogRestart }
            - { name: kernel.event_listener, event: watchdog.door_opening, method: onDoorOpening }
            - { name: kernel.event_listener, event: watchdog.door_closed, method: onDoorClosed }
            - { name: kernel.event_listener, event: watchdog.hardware_error, method: onHardwareError }

    gdc.door_state_save_path:
        class: SplFileInfo
        arguments:
            - %gdc.door_state_save_path%

    gdc.door_state_writer:
        class: GDCBundle\Service\DoorStateWriter
        arguments:
            - @gdc.door_state_save_path
        tags:
            - { name: kernel.event_listener, event: gdc.auto_sequence_started, method: onAutoSequenceStarted }
            - { name: kernel.event_listener, event: gdc.auto_sequence_terminated, method: onAutoSequenceTerminated }

    gdc.watchdog:
        class: GDC\WatchDog\WatchDog
        arguments:
            - @gdc.door
            - @gdc.watchdog_messenger
            - @gdc.door_state_writer
            - @event_dispatcher

    gdc.command_queue_entry_repository:
        class: GDCBundle\Entity\CommandQueueEntryRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - GDCBundle:CommandQueueEntry

    gdc.sensor_log_entry_repository:
        class: GDCBundle\Entity\SensorLogEntryRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - GDCBundle:SensorLogEntry

    gdc.command_processor:
        class: GDCBundle\Service\CommandProcessor
        arguments:
            - @gdc.command_queue_entry_repository
            - @event_dispatcher

    gdc.sensor_logger_factory:
        class: GDCBundle\Service\SensorLogger\Factory
        arguments:
            - @gdc.sensor_log_entry_repository
            - @gdc.piface_input_pin.door_closed
            - @gdc.piface_input_pin.door_opened
            - @gdc.piface_input_pin.photo_interrupter

    gdc.sensor_logger:
        class: GDCBundle\Service\SensorLogger\SensorLogger
        factory_service: gdc.sensor_logger_factory
        factory_method: createInstance

    gdc.event_loop:
        class: GDCBundle\Service\EventLoop
        arguments:
            - @gdc.command_processor
            - @gdc.watchdog
            - @gdc.sensor_logger

    gdc.auto_sequence.factory:
        class: GDCBundle\Service\AutoSequence\Factory
        arguments:
            - @gdc.door
            - @gdc.piface_input_pin.photo_interrupter

    gdc.auto_sequence.worker:
        class: GDCBundle\Service\AutoSequence\Worker
        arguments:
            - @gdc.auto_sequence.factory
            - @event_dispatcher
        tags:
            - { name: kernel.event_listener, event: gdc.command_issued, method: onCommandIssued }
