gdc_homepage:
    pattern:  /
    defaults: { _controller: GDCCoreBundle:Default:index }

gdc_trigger:
    pattern:  /trigger
    defaults: { _controller: GDCCoreBundle:Default:trigger }

gdc_snapshot:
    pattern:  /snapshot
    defaults: { _controller: GDCCoreBundle:Default:snapshot }

gdc_door_state:
    pattern:  /door-state
    defaults: { _controller: GDCCoreBundle:Default:doorState }
