parameters:
#    gdc.example.class: GDC\CoreBundle\Example

services:
#    gdc.example:
#        class: %gdc.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    gdc.piface_factory:
        class: GDC\Door\PiFaceFactory
        arguments:
            - %kernel.root_dir%/var/emulator
            - %gdc_use_piface_hardware%

    gdc.piface:
        class: Pkj\Raspberry\PiFace
        factory_service: gdc.piface_factory
        factory_method: createInstance

    gdc.door:
        class: GDC\Door
        arguments:
            - @gdc.piface

    gdc.watchdog_messenger:
        class: GDC\WatchDog\Messenger
        arguments:
            - @mailer
            - %kernel.environment%

    gdc.watchdog:
        class: GDC\WatchDog\WatchDog
        arguments:
            - @gdc.door
            - @gdc.watchdog_messenger

    gdc.camera_http_client:
        class: Guzzle\Http\Client
        arguments:
            - %camera_url%

    gdc.camera:
        class: GDC\Camera
        arguments:
            - @gdc.camera_http_client
            - %camera_username%
            - %camera_password%
